# Generated by Django 3.1.1 on 2020-09-26 08:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cpdaily',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='任务名字')),
                ('value', models.CharField(max_length=30, verbose_name='提交数值')),
            ],
        ),
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=30, verbose_name='学校名')),
                ('address', models.CharField(max_length=100, verbose_name='学校地址')),
                ('longitude', models.CharField(max_length=25, verbose_name='学校经度')),
                ('latitude', models.CharField(max_length=25, verbose_name='学校纬度')),
            ],
            options={
                'verbose_name': '学校信息',
                'verbose_name_plural': '学校信息',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=10, verbose_name='用户姓名')),
                ('student_number', models.CharField(default='', max_length=50, verbose_name='用户学工号')),
                ('password', models.CharField(default='', max_length=50, verbose_name='用户学工号密码')),
                ('open_id', models.CharField(max_length=100, verbose_name='用户openid')),
                ('expires', models.DateTimeField(verbose_name='用户过期时间')),
                ('email', models.CharField(max_length=30, verbose_name='用户邮箱')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='login.school', verbose_name='用户所属学校')),
            ],
            options={
                'verbose_name': '用户信息',
                'verbose_name_plural': '用户信息',
            },
        ),
    ]
