# Generated by Django 3.1.1 on 2020-09-29 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0002_auto_20200926_2238'),
    ]

    operations = [
        migrations.AddField(
            model_name='cpdaily',
            name='task_name',
            field=models.CharField(default='', max_length=30, verbose_name='任务名字'),
        ),
        migrations.AddField(
            model_name='user',
            name='photo',
            field=models.URLField(default='', verbose_name='图片地址'),
        ),
        migrations.AlterField(
            model_name='cpdaily',
            name='name',
            field=models.CharField(default='', max_length=30, verbose_name='任务描述'),
        ),
    ]
