# Generated by Django 3.1.1 on 2020-09-29 13:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0003_auto_20200929_2052'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Cpdaily',
        ),
    ]
