# Generated by Django 3.1.1 on 2020-09-30 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0004_delete_cpdaily'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(db_index=True, default='', max_length=50, verbose_name='用户学工号密码'),
        ),
        migrations.AlterField(
            model_name='user',
            name='student_number',
            field=models.CharField(db_index=True, default='', max_length=50, verbose_name='用户学工号'),
        ),
    ]
