# Generated by Django 2.2.12 on 2020-10-02 02:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0006_auto_20201001_1948'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='photo',
            field=models.URLField(blank=True, null=True, verbose_name='图片地址'),
        ),
    ]
