# Generated by Django 2.2.12 on 2020-10-03 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0007_auto_20201002_1006'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='time',
            field=models.IntegerField(choices=[(7, '7点查寝'), (9, '9点查寝'), (1030, '10点30查寝')], default=7, verbose_name='查寝时间'),
        ),
    ]
