# Generated by Django 2.2.12 on 2020-10-05 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0008_user_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='time',
        ),
        migrations.AddField(
            model_name='user',
            name='attendance_time',
            field=models.IntegerField(choices=[(7, '7点查寝'), (8, '8点查寝'), (9, '9点查寝'), (1030, '10点30查寝')], db_index=True, default=7, verbose_name='查寝时间'),
        ),
        migrations.AddField(
            model_name='user',
            name='morning_time',
            field=models.IntegerField(choices=[(7, '7点早签'), (8, '8点早签'), (9, '9点早签')], db_index=True, default=7, verbose_name='早签时间'),
        ),
        migrations.AddField(
            model_name='user',
            name='night_time',
            field=models.IntegerField(choices=[(7, '7点晚签'), (8, '8点晚签'), (9, '9点晚签')], db_index=True, default=7, verbose_name='晚签时间'),
        ),
    ]
