# Generated by Django 2.2.12 on 2020-10-05 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0009_auto_20201005_0934'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='expires',
            field=models.DateTimeField(db_index=True, verbose_name='用户过期时间'),
        ),
    ]
