# Generated by Django 2.2.12 on 2020-10-09 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0010_auto_20201005_1140'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='attendance_time',
            field=models.IntegerField(choices=[(7, '7点查寝'), (8, '8点查寝'), (9, '9点查寝'), (930, '9点30查寝'), (10, '10点查寝'), (1030, '10点30查寝')], db_index=True, default=7, verbose_name='查寝时间'),
        ),
    ]
