# Generated by Django 2.2.12 on 2020-10-11 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0014_auto_20201011_1049'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='photo',
            field=models.CharField(blank=True, default='', max_length=300, verbose_name='图片名字'),
        ),
    ]
