# Generated by Django 2.2.12 on 2020-10-16 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0015_auto_20201011_1532'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='status',
            field=models.IntegerField(choices=[(0, '暂停'), (1, '打卡')], default=1, verbose_name='状态'),
        ),
    ]
