# Generated by Django 2.2.12 on 2020-10-16 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0016_user_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='photo',
            field=models.CharField(blank=True, default='[]', max_length=500, verbose_name='图片名字'),
        ),
    ]
