# Generated by Django 2.2.12 on 2020-10-16 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0017_auto_20201016_1202'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='expires',
            field=models.DateTimeField(verbose_name='用户过期时间'),
        ),
        migrations.AlterField(
            model_name='user',
            name='status',
            field=models.IntegerField(choices=[(0, '暂停'), (1, '打卡')], db_index=True, default=1, verbose_name='状态'),
        ),
    ]
