# Generated by Django 2.2.12 on 2020-10-16 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0018_auto_20201016_1331'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='status',
            field=models.IntegerField(choices=[(0, '暂停打卡'), (1, '正常打卡')], db_index=True, default=1, verbose_name='状态'),
        ),
    ]
