# Generated by Django 2.2.12 on 2020-11-10 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0019_auto_20201016_1533'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='latitude',
            field=models.CharField(default='', max_length=25, verbose_name='地点纬度'),
        ),
        migrations.AddField(
            model_name='user',
            name='location',
            field=models.IntegerField(choices=[(0, '在学校'), (1, '自定义')], default=0, verbose_name='打卡地点'),
        ),
        migrations.AddField(
            model_name='user',
            name='longitude',
            field=models.CharField(default='', max_length=25, verbose_name='地点经度'),
        ),
    ]
