# Generated by Django 2.2.12 on 2020-11-13 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0021_user_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='address',
            field=models.CharField(default='无', max_length=100, verbose_name='打卡地址'),
        ),
        migrations.AlterField(
            model_name='user',
            name='latitude',
            field=models.CharField(default='无', max_length=25, verbose_name='地点纬度'),
        ),
        migrations.AlterField(
            model_name='user',
            name='longitude',
            field=models.CharField(default='无', max_length=25, verbose_name='地点经度'),
        ),
    ]
